# Generated by Django 4.0.4 on 2024-07-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='box',
        ),
    ]
