# Generated by Django 4.0.4 on 2024-06-30 20:05

import cards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_classeur_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classeur',
            name='titre',
        ),
        migrations.AddField(
            model_name='card',
            name='classeur',
            field=models.ForeignKey(default=cards.models.get_default_classeur, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.classeur'),
        ),
        migrations.AddField(
            model_name='classeur',
            name='name',
            field=models.CharField(default='Default Classeur', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
