# Generated by Django 4.0.4 on 2024-10-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_user_classeur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
