# Generated by Django 4.0.4 on 2024-06-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_classeur_titre_card_classeur_classeur_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='classeur',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
