# Generated by Django 4.0.4 on 2024-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='index',
        ),
        migrations.AddField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
