# Generated by Django 4.0.4 on 2024-06-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_name_classeur_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classeur',
            old_name='name',
            new_name='titre',
        ),
    ]
