# Generated by Django 4.2.16 on 2024-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_index_card_box_alter_card_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeur',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
