# Generated by Django 4.2.16 on 2024-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_classeur_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeur',
            name='category',
            field=models.CharField(choices=[('FR', 'Français'), ('DE', 'Allemand'), ('IT', 'Italien'), ('ES', 'Espagnol')], default='FR', max_length=2),
        ),
    ]
