# Generated by Django 4.2.16 on 2024-11-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_classeur_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeur',
            name='category',
            field=models.CharField(choices=[('DE', 'Allemand'), ('IT', 'Italien'), ('ES', 'Espagnol'), ('EN', 'Anglais')], default='FR', max_length=2),
        ),
    ]
